name: build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build image
        run: make build-image

      - name: push image
        if: github.ref_name == 'main'
        run: make push-image

      - name: retag latest
        if: github.ref_name == 'main'
        run: make retag-image
        env:
          VERSION: main-${{ github.sha }}-${{ github.run_number }}

      - name: draft release
        id: draft_release
        if: github.ref_name == 'main'
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
